# Setup
title:               'loulu's'
tagline:             'blog'
description:         'Just a simple blog'
url:                 https://loulu.xyz/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Louise
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
